#!/bin/bash

IFS=:

for dir in $PATH; do
    if [ -z "$dir" ]; then dir=.; fi

    if ! [ -e "$dir" ]; then 
        echo "$dir does not exist"
    elif ! [ -d "$dir" ]; then
        echo "$dir isn't a directory"
    else 
        ls -ld $dir
    fi
done

echo

for dir in $PATH; do
    echo $dir
done
